name: Build and Deploy

on:
  push:
    branches:
      - main  # This runs the workflow when code is pushed to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a stable version of Node.js

      - name: Install dependencies
        run: npm install

      # Step 3: Verify Astro installation
      - name: Verify Astro installation
        run: npm ls astro

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: List files after build (debugging)
      - name: List files after build
        run: ls -la

      # Step 6: Checkout deploy branch
      - name: Checkout deploy branch
        run: |
          git fetch origin
          git checkout -b deploy || git checkout deploy

      # Step 7: Check if dist folder exists, then copy it
      - name: Check and copy dist folder to deploy branch
        run: |
          if [ -d "./dist" ]; then
            rm -rf ./dist/
            cp -r ./dist ./ 
          else
            echo "No dist folder found, skipping copy."
            exit 1
          fi

      # Step 8: Commit changes and push to the deploy branch
      - name: Commit and push dist to deploy branch
        run: |
          git add dist/
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -m "Deploy build"
          git push origin deploy
