name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js 21
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build
      - name: Run build
        run: npm run build

      # Step 5: Check if dist folder exists
      - name: Verify dist folder exists
        run: |
          if [ ! -d "./dist" ]; then
            echo "Dist folder does not exist! Exiting.";
            exit 1;
          fi

      # Step 6: Create deploy branch if it doesn't exist and deploy the build
      - name: Deploy to deploy branch
        run: |
            git fetch origin
            if git show-ref --quiet refs/heads/deploy; then
                git checkout deploy
            else
                git checkout --orphan deploy
            fi

            # Set up Git user info for commits
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"

            # Remove all files except dist/ folder
            find . -maxdepth 1 -not -name "dist" -not -name ".git" -exec rm -rf {} \;

            # Copy dist folder contents to root (or wherever you need them)
            cp -r dist/* .  # Make sure you're copying the actual files from dist

            # Commit and push to the deploy branch
            git add .  # Only the new contents of the dist directory
            git commit -m "Deploy new build from dist"

            git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin deploy --force